baseURL: https://estacion-r.netlify.app/
title: "Estación 🇷"
popup: true
languageCode: es-AR
theme: hugo-theme-hello-friend-ng
PygmentsCodeFences: yes
PygmentsStyle: monokailight
#PygmentsStyle: monokai
#PygmentsStyle: arduino
paginate: 10
rssLimit: 10
# copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
#   4.0 International License.
archetypeDir: archetypes
contentDir: content
dataDir: data
layoutDir: layouts
publishDir: public
googleAnalytics: "G-0ZC91NVHQK"
buildDrafts: no
buildFuture: no
buildExpired: no
canonifyURLs: yes
enableRobotsTXT: yes
enableGitInfo: no
enableEmoji: yes
enableMissingTranslationPlaceholders: no
disableRSS: no
disableSitemap: no
disable404: no
disableHugoGeneratorInject: no
permalinks:
  posts: /posts/:year/:month/:title/
author:
  name: "Pablo Tiscornia"
blackfriday:
  hrefTargetBlank: yes
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  customCSS: []
  customJS: []
  dateform: Jan 2, 2006
  dateformNum: '2006-01-02'
  dateformNumTime: 2006-01-02 15:04
  dateformShort: Jan 2
  description: Nice theme for homepages and blogs
  disableReadOtherPosts: no
  enableGlobalLanguageMenu: no
  enableSharingButtons: yes
  enableThemeToggle: no
  favicon:
    color:
      mask: '#1b1c1d'
      msapplication: '#1b1c1d'
      theme: '#1b1c1d'
  footer:
    author: yes
    bottomText:
      - Powered by <a href="http://gohugo.io">Hugo</a>
      - Made by <a href="https://github.com/rhazdon">Djordje Atlialp</a>
    copyright: no
    rss: yes
    topText: []
    trademark: yes
  homeSubtitle: ""
  images: ''
  justifyContent: no
  keywords: ''
  logo:
    logoHomeLink: /
    logoMark: '>'
    logoText: $ cd/estacion-r
  social:
    - name: Linktree
      url: https://linktr.ee/estacion_r
    - name: email
      url: "pablotiscornia@estacion-r.com"
menu:
  main:
    - name: Blog
      url: posts/
      weight: 10
    - name: Enseñar + R
      url: cursos_r/
      weight: 20
    - name: Autor
      url: perfil/
      weight: 30
    - name: Proyectos
      url: proyectos/
      weight: 40
    - name: Suscripción
      url: suscripcion/
      weight: 50
    # - name: Aportes
    #   url: aportes/
    #   weight: 50  
markup:
  goldmark:
    renderer:
      unsafe: true
